export const REFRESH_TOKEN_REJECTED_ERROR = 'REFRESH_TOKEN_REJECTED'
export const INVALID_RESPONSE_ERROR = 'INVALID_RESPONSE_ERROR'
export const REJECTED_AUTHENTICATION_ERROR = 'REJECTED_AUTHENTICATION_ERROR'